### ISSUE TITLE
How to use this plugin to send & receive intent from different apps ?

### ISSUE THREAD

**Issue by givemesumthing** [2skydev/capacitor-intent-resolver#1]
How to use this plugin to send & receive intent from different apps ? Is this plugin still valid for sdk 30+ and ionic 5/6 ?

**Comment by 2skydev** [comment]
Sorry, we are no longer performing maintenance.
We recommend that you do not use this plugin.

If you are looking for an issue related to the `intent`, please check the official document below
https://capacitorjs.com/docs/plugins/android#presenting-native-screens

**Comment by 2skydev** [comment]
This plugin only performs the following actions:

https://github.com/2skydev/capacitor-intent-resolver/blob/master/android/src/main/java/com/capacitor/intent/resolver/CapacitorIntentResolver.java
